name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: advance-replica-438505-c4 # Updated project ID
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry (optional if using GCR)
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/advance-replica-438505-c4/my-service:${{ github.sha }} . # Updated project ID
        docker push gcr.io/advance-replica-438505-c4/my-service:${{ github.sha }} # Updated project ID

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy gitactnsgglecldrunwrkflwcicd \
          --image gcr.io/advance-replica-438505-c4/my-service:${{ github.sha }} \ # Updated project ID
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --timeout 300s \
          --min-instances 1 \
          --max-instances 10 \
          --port 8080
